/*
  # Add IPL 2025 Players

  1. Data Changes
    - Insert players from all IPL teams for the 2025 season
    - Each player record includes:
      - name
      - team
      - role (Batsman, Bowler, All-Rounder, Wicket Keeper)

  2. Notes
    - Players are grouped by their respective teams
    - Roles are standardized across all entries
*/

-- CSK Players
INSERT INTO players (name, team, role) VALUES
('MS Dhoni', 'CSK', 'Wicket Keeper'),
('Ruturaj Gaikwad', 'CSK', 'Batsman'),
('Devon Conway', 'CSK', 'Batsman'),
('Ajinkya Rahane', 'CSK', 'Batsman'),
('Shaik Rasheed', 'CSK', 'Batsman'),
('Ravindra Jadeja', 'CSK', 'All-Rounder'),
('Mitchell Santner', 'CSK', 'All-Rounder'),
('Moeen Ali', 'CSK', 'All-Rounder'),
('Shivam Dube', 'CSK', 'All-Rounder'),
('Nishant Sindhu', 'CSK', 'All-Rounder'),
('Deepak Chahar', 'CSK', 'Bowler'),
('Tushar Deshpande', 'CSK', 'Bowler'),
('Matheesha Pathirana', 'CSK', 'Bowler'),
('Simarjeet Singh', 'CSK', 'Bowler'),
('Prashant Solanki', 'CSK', 'Bowler'),
('Maheesh Theekshana', 'CSK', 'Bowler'),
('Mukesh Choudhary', 'CSK', 'Bowler'),
('Ajay Mandal', 'CSK', 'Bowler'),
('Rajvardhan Hangargekar', 'CSK', 'Bowler'),
('Sameer Rizvi', 'CSK', 'Batsman'),
('Rachin Ravindra', 'CSK', 'All-Rounder'),
('Shardul Thakur', 'CSK', 'Bowler'),
('Daryl Mitchell', 'CSK', 'All-Rounder'),
('Avanish Rao Aravelly', 'CSK', 'Wicket Keeper');

-- DC Players
INSERT INTO players (name, team, role) VALUES
('Rishabh Pant', 'DC', 'Wicket Keeper'),
('David Warner', 'DC', 'Batsman'),
('Prithvi Shaw', 'DC', 'Batsman'),
('Yash Dhull', 'DC', 'Batsman'),
('Swastik Chikara', 'DC', 'Batsman'),
('Shai Hope', 'DC', 'Wicket Keeper'),
('Axar Patel', 'DC', 'All-Rounder'),
('Mitchell Marsh', 'DC', 'All-Rounder'),
('Lalit Yadav', 'DC', 'All-Rounder'),
('Pravin Dubey', 'DC', 'All-Rounder'),
('Anrich Nortje', 'DC', 'Bowler'),
('Lungi Ngidi', 'DC', 'Bowler'),
('Khaleel Ahmed', 'DC', 'Bowler'),
('Ishant Sharma', 'DC', 'Bowler'),
('Mukesh Kumar', 'DC', 'Bowler'),
('Kuldeep Yadav', 'DC', 'Bowler'),
('Praveen Dubey', 'DC', 'Bowler'),
('Vicky Ostwal', 'DC', 'Bowler'),
('Ricky Bhui', 'DC', 'Batsman'),
('Kumar Kushagra', 'DC', 'Wicket Keeper'),
('Rasikh Dar', 'DC', 'Bowler'),
('Abhishek Porel', 'DC', 'Wicket Keeper'),
('Jake Fraser-McGurk', 'DC', 'Batsman'),
('Jhye Richardson', 'DC', 'Bowler'),
('Harry Brook', 'DC', 'Batsman');

-- GT Players
INSERT INTO players (name, team, role) VALUES
('Hardik Pandya', 'GT', 'All-Rounder'),
('Shubman Gill', 'GT', 'Batsman'),
('Kane Williamson', 'GT', 'Batsman'),
('Sai Sudharsan', 'GT', 'Batsman'),
('David Miller', 'GT', 'Batsman'),
('Matthew Wade', 'GT', 'Wicket Keeper'),
('Wriddhiman Saha', 'GT', 'Wicket Keeper'),
('Rashid Khan', 'GT', 'All-Rounder'),
('Rahul Tewatia', 'GT', 'All-Rounder'),
('Vijay Shankar', 'GT', 'All-Rounder'),
('Mohammed Shami', 'GT', 'Bowler'),
('Alzarri Joseph', 'GT', 'Bowler'),
('Mohit Sharma', 'GT', 'Bowler'),
('Sai Kishore', 'GT', 'Bowler'),
('Jayant Yadav', 'GT', 'Bowler'),
('Joshua Little', 'GT', 'Bowler'),
('Noor Ahmad', 'GT', 'Bowler'),
('Umesh Yadav', 'GT', 'Bowler'),
('Kartik Tyagi', 'GT', 'Bowler'),
('Azmatullah Omarzai', 'GT', 'All-Rounder'),
('Manav Suthar', 'GT', 'Bowler'),
('Spencer Johnson', 'GT', 'Bowler'),
('Robin Minz', 'GT', 'Wicket Keeper'),
('Shahrukh Khan', 'GT', 'Batsman');

-- KKR Players
INSERT INTO players (name, team, role) VALUES
('Shreyas Iyer', 'KKR', 'Batsman'),
('Nitish Rana', 'KKR', 'Batsman'),
('Rinku Singh', 'KKR', 'Batsman'),
('Rahmanullah Gurbaz', 'KKR', 'Wicket Keeper'),
('Jason Roy', 'KKR', 'Batsman'),
('Angkrish Raghuvanshi', 'KKR', 'Batsman'),
('Andre Russell', 'KKR', 'All-Rounder'),
('Venkatesh Iyer', 'KKR', 'All-Rounder'),
('Sunil Narine', 'KKR', 'All-Rounder'),
('Anukul Roy', 'KKR', 'All-Rounder'),
('Varun Chakravarthy', 'KKR', 'Bowler'),
('Vaibhav Arora', 'KKR', 'Bowler'),
('Harshit Rana', 'KKR', 'Bowler'),
('Suyash Sharma', 'KKR', 'Bowler'),
('Mitchell Starc', 'KKR', 'Bowler'),
('Chetan Sakariya', 'KKR', 'Bowler'),
('Manish Pandey', 'KKR', 'Batsman'),
('K.L Bharat', 'KKR', 'Wicket Keeper'),
('Ramandeep Singh', 'KKR', 'All-Rounder'),
('Sakib Hussain', 'KKR', 'Bowler'),
('Sherfane Rutherford', 'KKR', 'All-Rounder'),
('Gus Atkinson', 'KKR', 'Bowler');

-- LSG Players
INSERT INTO players (name, team, role) VALUES
('KL Rahul', 'LSG', 'Wicket Keeper'),
('Quinton de Kock', 'LSG', 'Wicket Keeper'),
('Nicholas Pooran', 'LSG', 'Wicket Keeper'),
('Ayush Badoni', 'LSG', 'Batsman'),
('Kyle Mayers', 'LSG', 'All-Rounder'),
('Marcus Stoinis', 'LSG', 'All-Rounder'),
('Deepak Hooda', 'LSG', 'All-Rounder'),
('Krunal Pandya', 'LSG', 'All-Rounder'),
('Krishnappa Gowtham', 'LSG', 'All-Rounder'),
('Mark Wood', 'LSG', 'Bowler'),
('Mohsin Khan', 'LSG', 'Bowler'),
('Ravi Bishnoi', 'LSG', 'Bowler'),
('Mayank Yadav', 'LSG', 'Bowler'),
('Yash Thakur', 'LSG', 'Bowler'),
('Prerak Mankad', 'LSG', 'All-Rounder'),
('Amit Mishra', 'LSG', 'Bowler'),
('Naveen-ul-Haq', 'LSG', 'Bowler'),
('Shivam Mavi', 'LSG', 'Bowler'),
('Arshin Kulkarni', 'LSG', 'All-Rounder'),
('M Siddharth', 'LSG', 'Bowler'),
('Ashton Turner', 'LSG', 'Batsman'),
('David Willey', 'LSG', 'All-Rounder'),
('Devdutt Padikkal', 'LSG', 'Batsman');

-- MI Players
INSERT INTO players (name, team, role) VALUES
('Hardik Pandya', 'MI', 'All-Rounder'),
('Rohit Sharma', 'MI', 'Batsman'),
('Dewald Brevis', 'MI', 'Batsman'),
('Suryakumar Yadav', 'MI', 'Batsman'),
('Ishan Kishan', 'MI', 'Wicket Keeper'),
('Tilak Varma', 'MI', 'Batsman'),
('Tim David', 'MI', 'All-Rounder'),
('Vishnu Vinod', 'MI', 'Wicket Keeper'),
('Arjun Tendulkar', 'MI', 'All-Rounder'),
('Shams Mulani', 'MI', 'All-Rounder'),
('Nehal Wadhera', 'MI', 'All-Rounder'),
('Jasprit Bumrah', 'MI', 'Bowler'),
('Kumar Kartikeya', 'MI', 'Bowler'),
('Akash Madhwal', 'MI', 'Bowler'),
('Jason Behrendorff', 'MI', 'Bowler'),
('Romario Shepherd', 'MI', 'All-Rounder'),
('Shreyas Gopal', 'MI', 'Bowler'),
('Nuwan Thushara', 'MI', 'Bowler'),
('Naman Dhir', 'MI', 'Batsman'),
('Anshul Kamboj', 'MI', 'Bowler'),
('Mohammad Nabi', 'MI', 'All-Rounder'),
('Shivalik Sharma', 'MI', 'All-Rounder'),
('Gerald Coetzee', 'MI', 'Bowler'),
('Dilshan Madushanka', 'MI', 'Bowler'),
('Kwena Maphaka', 'MI', 'Bowler');

-- PBKS Players
INSERT INTO players (name, team, role) VALUES
('Shikhar Dhawan', 'PBKS', 'Batsman'),
('Jonny Bairstow', 'PBKS', 'Wicket Keeper'),
('Prabhsimran Singh', 'PBKS', 'Wicket Keeper'),
('Jitesh Sharma', 'PBKS', 'Wicket Keeper'),
('Liam Livingstone', 'PBKS', 'All-Rounder'),
('Harpreet Bhatia', 'PBKS', 'Batsman'),
('Rilee Rossouw', 'PBKS', 'Batsman'),
('Sam Curran', 'PBKS', 'All-Rounder'),
('Sikandar Raza', 'PBKS', 'All-Rounder'),
('Shivam Singh', 'PBKS', 'All-Rounder'),
('Harpreet Brar', 'PBKS', 'All-Rounder'),
('Rahul Chahar', 'PBKS', 'Bowler'),
('Arshdeep Singh', 'PBKS', 'Bowler'),
('Kagiso Rabada', 'PBKS', 'Bowler'),
('Nathan Ellis', 'PBKS', 'Bowler'),
('Vidwath Kaverappa', 'PBKS', 'Bowler'),
('Chris Woakes', 'PBKS', 'All-Rounder'),
('Harshal Patel', 'PBKS', 'Bowler'),
('Ashutosh Sharma', 'PBKS', 'Batsman'),
('Vishwanath Singh', 'PBKS', 'Batsman'),
('Shashank Singh', 'PBKS', 'All-Rounder'),
('Tanay Thyagarajan', 'PBKS', 'Bowler'),
('Prince Choudhary', 'PBKS', 'Bowler'),
('Rishi Dhawan', 'PBKS', 'All-Rounder');

-- RCB Players
INSERT INTO players (name, team, role) VALUES
('Faf du Plessis', 'RCB', 'Batsman'),
('Glenn Maxwell', 'RCB', 'All-Rounder'),
('Virat Kohli', 'RCB', 'Batsman'),
('Rajat Patidar', 'RCB', 'Batsman'),
('Anuj Rawat', 'RCB', 'Wicket Keeper'),
('Dinesh Karthik', 'RCB', 'Wicket Keeper'),
('Suyash Prabhudessai', 'RCB', 'All-Rounder'),
('Will Jacks', 'RCB', 'All-Rounder'),
('Mahipal Lomror', 'RCB', 'All-Rounder'),
('Karn Sharma', 'RCB', 'Bowler'),
('Manoj Bhandage', 'RCB', 'All-Rounder'),
('Mohammed Siraj', 'RCB', 'Bowler'),
('Akash Deep', 'RCB', 'Bowler'),
('Reece Topley', 'RCB', 'Bowler'),
('Himanshu Sharma', 'RCB', 'Bowler'),
('Rajan Kumar', 'RCB', 'Bowler'),
('Mayank Dagar', 'RCB', 'All-Rounder'),
('Vijaykumar Vyshak', 'RCB', 'Bowler'),
('Swapnil Singh', 'RCB', 'All-Rounder'),
('Tom Curran', 'RCB', 'All-Rounder'),
('Lockie Ferguson', 'RCB', 'Bowler'),
('Alzarri Joseph', 'RCB', 'Bowler'),
('Cameron Green', 'RCB', 'All-Rounder'),
('Yash Dayal', 'RCB', 'Bowler');

-- RR Players
INSERT INTO players (name, team, role) VALUES
('Sanju Samson', 'RR', 'Wicket Keeper'),
('Jos Buttler', 'RR', 'Wicket Keeper'),
('Yashasvi Jaiswal', 'RR', 'Batsman'),
('Shimron Hetmyer', 'RR', 'Batsman'),
('Dhruv Jurel', 'RR', 'Wicket Keeper'),
('Riyan Parag', 'RR', 'All-Rounder'),
('Donovan Ferreira', 'RR', 'Wicket Keeper'),
('Kunal Rathore', 'RR', 'Wicket Keeper'),
('Ravichandran Ashwin', 'RR', 'All-Rounder'),
('Trent Boult', 'RR', 'Bowler'),
('Yuzvendra Chahal', 'RR', 'Bowler'),
('Avesh Khan', 'RR', 'Bowler'),
('Navdeep Saini', 'RR', 'Bowler'),
('Sandeep Sharma', 'RR', 'Bowler'),
('Kuldeep Sen', 'RR', 'Bowler'),
('Rovman Powell', 'RR', 'Batsman'),
('Shubham Dubey', 'RR', 'Batsman'),
('Tom Kohler-Cadmore', 'RR', 'Wicket Keeper'),
('Abid Mushtaq', 'RR', 'Bowler'),
('Nandre Burger', 'RR', 'Bowler');

-- SRH Players
INSERT INTO players (name, team, role) VALUES
('Pat Cummins', 'SRH', 'All-Rounder'),
('Abdul Samad', 'SRH', 'All-Rounder'),
('Abhishek Sharma', 'SRH', 'All-Rounder'),
('Aiden Markram', 'SRH', 'Batsman'),
('Marco Jansen', 'SRH', 'All-Rounder'),
('Rahul Tripathi', 'SRH', 'Batsman'),
('Washington Sundar', 'SRH', 'All-Rounder'),
('Glenn Phillips', 'SRH', 'Wicket Keeper'),
('Heinrich Klaasen', 'SRH', 'Wicket Keeper'),
('Mayank Agarwal', 'SRH', 'Batsman'),
('Anmolpreet Singh', 'SRH', 'Batsman'),
('Mayank Markande', 'SRH', 'Bowler'),
('Bhuvneshwar Kumar', 'SRH', 'Bowler'),
('T Natarajan', 'SRH', 'Bowler'),
('Fazalhaq Farooqi', 'SRH', 'Bowler'),
('Umran Malik', 'SRH', 'Bowler'),
('Shahbaz Ahmed', 'SRH', 'All-Rounder'),
('Wanindu Hasaranga', 'SRH', 'All-Rounder'),
('Travis Head', 'SRH', 'Batsman'),
('Jaydev Unadkat', 'SRH', 'Bowler'),
('Akash Singh', 'SRH', 'Bowler'),
('Jhathavedh Subramanyan', 'SRH', 'Bowler'),
('Upendra Singh Yadav', 'SRH', 'Wicket Keeper'),
('Nitish Kumar Reddy', 'SRH', 'All-Rounder');